version: '3.7'
services:
  react:
    image: nilmontia/react
    build: ./doit-simple
  spring:
    image: nilmontia/spring
    build: ./First-app-spring
  mysql:
    image: mysql:5.7
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=doit
    volumes:
        - type: volume
          source: mysql
          target: /var/lib/mysql
  nginx:
    image: nilmontia/nginx
    ports:
    - target: 80
      published: 80
    depends_on:
      - react
      - spring
volumes:
  mysql:
